<?php
namespace console\controllers;

use yii\console\Controller;

class HelloController extends Controller
{
    public $message = 'hello world';

    public function options($actionID)
    {
        return ['message'];
        //return parent::options($actionID); // TODO: Change the autogenerated stub
    }

    public function optionAliases()
    {
        return [
            'm'=>'message'
        ];
        //return parent::optionAliases(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        echo $this->message."\n";
    }
}