<?php


namespace console\controllers;

use yii\console\Controller;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Exchange\AMQPExchangeType;
use PhpAmqpLib\Message\AMQPMessage;
class PublishController extends Controller
{
    public $exchange = 'router';
    public $queue = 'msgs';
    public $message = 'hello world';

    public function options($actionID)
    {
        return [
            'message'
        ];
        //return parent::options($actionID); // TODO: Change the autogenerated stub
    }

    public function optionAliases()
    {
        return [
            'm'=>'message'
        ];
        //return parent::optionAliases(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $connection = new AMQPStreamConnection('localhost', '5672', 'guest', 'guest', '/');
        $channel = $connection->channel();

        $channel->queue_declare($this->queue, false, true, false, false);

        $channel->exchange_declare($this->exchange, AMQPExchangeType::DIRECT, false, true, false);

        $messageBody = $this->message;
        $message = new AMQPMessage($messageBody, array('content_type' => 'text/plain', 'delivery_mode'=>AMQPMessage::DELIVERY_MODE_PERSISTENT));
        $channel->basic_publish($message, $this->exchange);


        $channel->close();
        $connection->close();

    }
}